### PR TITLE
added placeholder image to replace broken image link when creating a …

### PR DESCRIPTION
**Pull request by MichealGarcia**
# Description

Added a placeholder to replace a broken image link when adding a new image.

I updated the frontend directories itempreview.js to import a local placeholder image saved to our frontend/imgs folder.

Then replaced the existing html code src={this.image} to a src={this.image ? this.image : placeholder}

added_placeholder

import_placeholder

updatedcode

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @MichealGarcia, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by MichealGarcia** [comment]
# Description

Added a placeholder to replace a broken image link when adding a new image.

I updated the frontend directories itempreview.js to import a local placeholder image saved to our frontend/imgs folder.

Then replaced the existing html code src={this.image} to a src={this.image ? this.image : placeholder}



added_placeholder

import_placeholder

updatedcode

**Comment by MichealGarcia** [comment]
I fixed the issue, I didn't add the code after taking first image

**Comment by MichealGarcia** [comment]
Pushed fixed code, after removing ternary

**Comment by MichealGarcia** [comment]
found issue in package.json

**Comment by MichealGarcia** [comment]
updated my own linter??

**Comment by MichealGarcia** [comment]
Needed to run prettier on frontend subdirectory

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @MichealGarcia! You're now able to merge the PR.

**Pull request merged**
